package com.wyt.HikariCP.demo.mapper;

import com.wyt.HikariCP.demo.model.ChatDetail;
import com.wyt.HikariCP.demo.model.ChatDetailExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;

@Mapper
public interface ChatDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int countByExample(ChatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int deleteByExample(ChatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int insert(ChatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int insertSelective(ChatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    List<ChatDetail> selectByExample(ChatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    ChatDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ChatDetail record, @Param("example") ChatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ChatDetail record, @Param("example") ChatDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChatDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChatDetail record);

    @Transactional(timeout = 10)
    int countByLike(@Param("companyId") long companyId, @Param("likeStr") String likeStr);
}