package com.wyt.HikariCP.demo.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChatDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public ChatDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdIsNull() {
            addCriterion("chat_info_id is null");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdIsNotNull() {
            addCriterion("chat_info_id is not null");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdEqualTo(Long value) {
            addCriterion("chat_info_id =", value, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdNotEqualTo(Long value) {
            addCriterion("chat_info_id <>", value, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdGreaterThan(Long value) {
            addCriterion("chat_info_id >", value, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdGreaterThanOrEqualTo(Long value) {
            addCriterion("chat_info_id >=", value, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdLessThan(Long value) {
            addCriterion("chat_info_id <", value, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdLessThanOrEqualTo(Long value) {
            addCriterion("chat_info_id <=", value, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdIn(List<Long> values) {
            addCriterion("chat_info_id in", values, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdNotIn(List<Long> values) {
            addCriterion("chat_info_id not in", values, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdBetween(Long value1, Long value2) {
            addCriterion("chat_info_id between", value1, value2, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andChatInfoIdNotBetween(Long value1, Long value2) {
            addCriterion("chat_info_id not between", value1, value2, "chatInfoId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNull() {
            addCriterion("staff_id is null");
            return (Criteria) this;
        }

        public Criteria andStaffIdIsNotNull() {
            addCriterion("staff_id is not null");
            return (Criteria) this;
        }

        public Criteria andStaffIdEqualTo(Long value) {
            addCriterion("staff_id =", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotEqualTo(Long value) {
            addCriterion("staff_id <>", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThan(Long value) {
            addCriterion("staff_id >", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdGreaterThanOrEqualTo(Long value) {
            addCriterion("staff_id >=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThan(Long value) {
            addCriterion("staff_id <", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdLessThanOrEqualTo(Long value) {
            addCriterion("staff_id <=", value, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdIn(List<Long> values) {
            addCriterion("staff_id in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotIn(List<Long> values) {
            addCriterion("staff_id not in", values, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdBetween(Long value1, Long value2) {
            addCriterion("staff_id between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffIdNotBetween(Long value1, Long value2) {
            addCriterion("staff_id not between", value1, value2, "staffId");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNull() {
            addCriterion("staff_name is null");
            return (Criteria) this;
        }

        public Criteria andStaffNameIsNotNull() {
            addCriterion("staff_name is not null");
            return (Criteria) this;
        }

        public Criteria andStaffNameEqualTo(String value) {
            addCriterion("staff_name =", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotEqualTo(String value) {
            addCriterion("staff_name <>", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThan(String value) {
            addCriterion("staff_name >", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameGreaterThanOrEqualTo(String value) {
            addCriterion("staff_name >=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThan(String value) {
            addCriterion("staff_name <", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLessThanOrEqualTo(String value) {
            addCriterion("staff_name <=", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameLike(String value) {
            addCriterion("staff_name like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotLike(String value) {
            addCriterion("staff_name not like", value, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameIn(List<String> values) {
            addCriterion("staff_name in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotIn(List<String> values) {
            addCriterion("staff_name not in", values, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameBetween(String value1, String value2) {
            addCriterion("staff_name between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andStaffNameNotBetween(String value1, String value2) {
            addCriterion("staff_name not between", value1, value2, "staffName");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNull() {
            addCriterion("event_type is null");
            return (Criteria) this;
        }

        public Criteria andEventTypeIsNotNull() {
            addCriterion("event_type is not null");
            return (Criteria) this;
        }

        public Criteria andEventTypeEqualTo(Byte value) {
            addCriterion("event_type =", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotEqualTo(Byte value) {
            addCriterion("event_type <>", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThan(Byte value) {
            addCriterion("event_type >", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("event_type >=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThan(Byte value) {
            addCriterion("event_type <", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeLessThanOrEqualTo(Byte value) {
            addCriterion("event_type <=", value, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeIn(List<Byte> values) {
            addCriterion("event_type in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotIn(List<Byte> values) {
            addCriterion("event_type not in", values, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeBetween(Byte value1, Byte value2) {
            addCriterion("event_type between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andEventTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("event_type not between", value1, value2, "eventType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNull() {
            addCriterion("content_type is null");
            return (Criteria) this;
        }

        public Criteria andContentTypeIsNotNull() {
            addCriterion("content_type is not null");
            return (Criteria) this;
        }

        public Criteria andContentTypeEqualTo(Byte value) {
            addCriterion("content_type =", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotEqualTo(Byte value) {
            addCriterion("content_type <>", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThan(Byte value) {
            addCriterion("content_type >", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("content_type >=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThan(Byte value) {
            addCriterion("content_type <", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeLessThanOrEqualTo(Byte value) {
            addCriterion("content_type <=", value, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeIn(List<Byte> values) {
            addCriterion("content_type in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotIn(List<Byte> values) {
            addCriterion("content_type not in", values, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeBetween(Byte value1, Byte value2) {
            addCriterion("content_type between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("content_type not between", value1, value2, "contentType");
            return (Criteria) this;
        }

        public Criteria andContentIsNull() {
            addCriterion("content is null");
            return (Criteria) this;
        }

        public Criteria andContentIsNotNull() {
            addCriterion("content is not null");
            return (Criteria) this;
        }

        public Criteria andContentEqualTo(String value) {
            addCriterion("content =", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotEqualTo(String value) {
            addCriterion("content <>", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThan(String value) {
            addCriterion("content >", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentGreaterThanOrEqualTo(String value) {
            addCriterion("content >=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThan(String value) {
            addCriterion("content <", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLessThanOrEqualTo(String value) {
            addCriterion("content <=", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentLike(String value) {
            addCriterion("content like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotLike(String value) {
            addCriterion("content not like", value, "content");
            return (Criteria) this;
        }

        public Criteria andContentIn(List<String> values) {
            addCriterion("content in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotIn(List<String> values) {
            addCriterion("content not in", values, "content");
            return (Criteria) this;
        }

        public Criteria andContentBetween(String value1, String value2) {
            addCriterion("content between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andContentNotBetween(String value1, String value2) {
            addCriterion("content not between", value1, value2, "content");
            return (Criteria) this;
        }

        public Criteria andEventTimeIsNull() {
            addCriterion("event_time is null");
            return (Criteria) this;
        }

        public Criteria andEventTimeIsNotNull() {
            addCriterion("event_time is not null");
            return (Criteria) this;
        }

        public Criteria andEventTimeEqualTo(Date value) {
            addCriterion("event_time =", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeNotEqualTo(Date value) {
            addCriterion("event_time <>", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeGreaterThan(Date value) {
            addCriterion("event_time >", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("event_time >=", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeLessThan(Date value) {
            addCriterion("event_time <", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeLessThanOrEqualTo(Date value) {
            addCriterion("event_time <=", value, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeIn(List<Date> values) {
            addCriterion("event_time in", values, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeNotIn(List<Date> values) {
            addCriterion("event_time not in", values, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeBetween(Date value1, Date value2) {
            addCriterion("event_time between", value1, value2, "eventTime");
            return (Criteria) this;
        }

        public Criteria andEventTimeNotBetween(Date value1, Date value2) {
            addCriterion("event_time not between", value1, value2, "eventTime");
            return (Criteria) this;
        }

        public Criteria andSendStatusIsNull() {
            addCriterion("send_status is null");
            return (Criteria) this;
        }

        public Criteria andSendStatusIsNotNull() {
            addCriterion("send_status is not null");
            return (Criteria) this;
        }

        public Criteria andSendStatusEqualTo(Byte value) {
            addCriterion("send_status =", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotEqualTo(Byte value) {
            addCriterion("send_status <>", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusGreaterThan(Byte value) {
            addCriterion("send_status >", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusGreaterThanOrEqualTo(Byte value) {
            addCriterion("send_status >=", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusLessThan(Byte value) {
            addCriterion("send_status <", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusLessThanOrEqualTo(Byte value) {
            addCriterion("send_status <=", value, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusIn(List<Byte> values) {
            addCriterion("send_status in", values, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotIn(List<Byte> values) {
            addCriterion("send_status not in", values, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusBetween(Byte value1, Byte value2) {
            addCriterion("send_status between", value1, value2, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andSendStatusNotBetween(Byte value1, Byte value2) {
            addCriterion("send_status not between", value1, value2, "sendStatus");
            return (Criteria) this;
        }

        public Criteria andResendTimesIsNull() {
            addCriterion("resend_times is null");
            return (Criteria) this;
        }

        public Criteria andResendTimesIsNotNull() {
            addCriterion("resend_times is not null");
            return (Criteria) this;
        }

        public Criteria andResendTimesEqualTo(Integer value) {
            addCriterion("resend_times =", value, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesNotEqualTo(Integer value) {
            addCriterion("resend_times <>", value, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesGreaterThan(Integer value) {
            addCriterion("resend_times >", value, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("resend_times >=", value, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesLessThan(Integer value) {
            addCriterion("resend_times <", value, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesLessThanOrEqualTo(Integer value) {
            addCriterion("resend_times <=", value, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesIn(List<Integer> values) {
            addCriterion("resend_times in", values, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesNotIn(List<Integer> values) {
            addCriterion("resend_times not in", values, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesBetween(Integer value1, Integer value2) {
            addCriterion("resend_times between", value1, value2, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andResendTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("resend_times not between", value1, value2, "resendTimes");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNull() {
            addCriterion("send_type is null");
            return (Criteria) this;
        }

        public Criteria andSendTypeIsNotNull() {
            addCriterion("send_type is not null");
            return (Criteria) this;
        }

        public Criteria andSendTypeEqualTo(Byte value) {
            addCriterion("send_type =", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotEqualTo(Byte value) {
            addCriterion("send_type <>", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThan(Byte value) {
            addCriterion("send_type >", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("send_type >=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThan(Byte value) {
            addCriterion("send_type <", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeLessThanOrEqualTo(Byte value) {
            addCriterion("send_type <=", value, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeIn(List<Byte> values) {
            addCriterion("send_type in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotIn(List<Byte> values) {
            addCriterion("send_type not in", values, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeBetween(Byte value1, Byte value2) {
            addCriterion("send_type between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andSendTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("send_type not between", value1, value2, "sendType");
            return (Criteria) this;
        }

        public Criteria andMidIsNull() {
            addCriterion("mid is null");
            return (Criteria) this;
        }

        public Criteria andMidIsNotNull() {
            addCriterion("mid is not null");
            return (Criteria) this;
        }

        public Criteria andMidEqualTo(Long value) {
            addCriterion("mid =", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotEqualTo(Long value) {
            addCriterion("mid <>", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThan(Long value) {
            addCriterion("mid >", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidGreaterThanOrEqualTo(Long value) {
            addCriterion("mid >=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThan(Long value) {
            addCriterion("mid <", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidLessThanOrEqualTo(Long value) {
            addCriterion("mid <=", value, "mid");
            return (Criteria) this;
        }

        public Criteria andMidIn(List<Long> values) {
            addCriterion("mid in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotIn(List<Long> values) {
            addCriterion("mid not in", values, "mid");
            return (Criteria) this;
        }

        public Criteria andMidBetween(Long value1, Long value2) {
            addCriterion("mid between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andMidNotBetween(Long value1, Long value2) {
            addCriterion("mid not between", value1, value2, "mid");
            return (Criteria) this;
        }

        public Criteria andClientMidIsNull() {
            addCriterion("client_mid is null");
            return (Criteria) this;
        }

        public Criteria andClientMidIsNotNull() {
            addCriterion("client_mid is not null");
            return (Criteria) this;
        }

        public Criteria andClientMidEqualTo(String value) {
            addCriterion("client_mid =", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidNotEqualTo(String value) {
            addCriterion("client_mid <>", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidGreaterThan(String value) {
            addCriterion("client_mid >", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidGreaterThanOrEqualTo(String value) {
            addCriterion("client_mid >=", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidLessThan(String value) {
            addCriterion("client_mid <", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidLessThanOrEqualTo(String value) {
            addCriterion("client_mid <=", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidLike(String value) {
            addCriterion("client_mid like", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidNotLike(String value) {
            addCriterion("client_mid not like", value, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidIn(List<String> values) {
            addCriterion("client_mid in", values, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidNotIn(List<String> values) {
            addCriterion("client_mid not in", values, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidBetween(String value1, String value2) {
            addCriterion("client_mid between", value1, value2, "clientMid");
            return (Criteria) this;
        }

        public Criteria andClientMidNotBetween(String value1, String value2) {
            addCriterion("client_mid not between", value1, value2, "clientMid");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNull() {
            addCriterion("create_datetime is null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIsNotNull() {
            addCriterion("create_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeEqualTo(Date value) {
            addCriterion("create_datetime =", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotEqualTo(Date value) {
            addCriterion("create_datetime <>", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThan(Date value) {
            addCriterion("create_datetime >", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_datetime >=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThan(Date value) {
            addCriterion("create_datetime <", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeLessThanOrEqualTo(Date value) {
            addCriterion("create_datetime <=", value, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeIn(List<Date> values) {
            addCriterion("create_datetime in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotIn(List<Date> values) {
            addCriterion("create_datetime not in", values, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeBetween(Date value1, Date value2) {
            addCriterion("create_datetime between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andCreateDatetimeNotBetween(Date value1, Date value2) {
            addCriterion("create_datetime not between", value1, value2, "createDatetime");
            return (Criteria) this;
        }

        public Criteria andMemoIsNull() {
            addCriterion("memo is null");
            return (Criteria) this;
        }

        public Criteria andMemoIsNotNull() {
            addCriterion("memo is not null");
            return (Criteria) this;
        }

        public Criteria andMemoEqualTo(String value) {
            addCriterion("memo =", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotEqualTo(String value) {
            addCriterion("memo <>", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThan(String value) {
            addCriterion("memo >", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoGreaterThanOrEqualTo(String value) {
            addCriterion("memo >=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThan(String value) {
            addCriterion("memo <", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLessThanOrEqualTo(String value) {
            addCriterion("memo <=", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoLike(String value) {
            addCriterion("memo like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotLike(String value) {
            addCriterion("memo not like", value, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoIn(List<String> values) {
            addCriterion("memo in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotIn(List<String> values) {
            addCriterion("memo not in", values, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoBetween(String value1, String value2) {
            addCriterion("memo between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andMemoNotBetween(String value1, String value2) {
            addCriterion("memo not between", value1, value2, "memo");
            return (Criteria) this;
        }

        public Criteria andDt1IsNull() {
            addCriterion("dt1 is null");
            return (Criteria) this;
        }

        public Criteria andDt1IsNotNull() {
            addCriterion("dt1 is not null");
            return (Criteria) this;
        }

        public Criteria andDt1EqualTo(Long value) {
            addCriterion("dt1 =", value, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1NotEqualTo(Long value) {
            addCriterion("dt1 <>", value, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1GreaterThan(Long value) {
            addCriterion("dt1 >", value, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1GreaterThanOrEqualTo(Long value) {
            addCriterion("dt1 >=", value, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1LessThan(Long value) {
            addCriterion("dt1 <", value, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1LessThanOrEqualTo(Long value) {
            addCriterion("dt1 <=", value, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1In(List<Long> values) {
            addCriterion("dt1 in", values, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1NotIn(List<Long> values) {
            addCriterion("dt1 not in", values, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1Between(Long value1, Long value2) {
            addCriterion("dt1 between", value1, value2, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt1NotBetween(Long value1, Long value2) {
            addCriterion("dt1 not between", value1, value2, "dt1");
            return (Criteria) this;
        }

        public Criteria andDt2IsNull() {
            addCriterion("dt2 is null");
            return (Criteria) this;
        }

        public Criteria andDt2IsNotNull() {
            addCriterion("dt2 is not null");
            return (Criteria) this;
        }

        public Criteria andDt2EqualTo(Long value) {
            addCriterion("dt2 =", value, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2NotEqualTo(Long value) {
            addCriterion("dt2 <>", value, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2GreaterThan(Long value) {
            addCriterion("dt2 >", value, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2GreaterThanOrEqualTo(Long value) {
            addCriterion("dt2 >=", value, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2LessThan(Long value) {
            addCriterion("dt2 <", value, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2LessThanOrEqualTo(Long value) {
            addCriterion("dt2 <=", value, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2In(List<Long> values) {
            addCriterion("dt2 in", values, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2NotIn(List<Long> values) {
            addCriterion("dt2 not in", values, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2Between(Long value1, Long value2) {
            addCriterion("dt2 between", value1, value2, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt2NotBetween(Long value1, Long value2) {
            addCriterion("dt2 not between", value1, value2, "dt2");
            return (Criteria) this;
        }

        public Criteria andDt3IsNull() {
            addCriterion("dt3 is null");
            return (Criteria) this;
        }

        public Criteria andDt3IsNotNull() {
            addCriterion("dt3 is not null");
            return (Criteria) this;
        }

        public Criteria andDt3EqualTo(Long value) {
            addCriterion("dt3 =", value, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3NotEqualTo(Long value) {
            addCriterion("dt3 <>", value, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3GreaterThan(Long value) {
            addCriterion("dt3 >", value, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3GreaterThanOrEqualTo(Long value) {
            addCriterion("dt3 >=", value, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3LessThan(Long value) {
            addCriterion("dt3 <", value, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3LessThanOrEqualTo(Long value) {
            addCriterion("dt3 <=", value, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3In(List<Long> values) {
            addCriterion("dt3 in", values, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3NotIn(List<Long> values) {
            addCriterion("dt3 not in", values, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3Between(Long value1, Long value2) {
            addCriterion("dt3 between", value1, value2, "dt3");
            return (Criteria) this;
        }

        public Criteria andDt3NotBetween(Long value1, Long value2) {
            addCriterion("dt3 not between", value1, value2, "dt3");
            return (Criteria) this;
        }

        public Criteria andVt1IsNull() {
            addCriterion("vt1 is null");
            return (Criteria) this;
        }

        public Criteria andVt1IsNotNull() {
            addCriterion("vt1 is not null");
            return (Criteria) this;
        }

        public Criteria andVt1EqualTo(String value) {
            addCriterion("vt1 =", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1NotEqualTo(String value) {
            addCriterion("vt1 <>", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1GreaterThan(String value) {
            addCriterion("vt1 >", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1GreaterThanOrEqualTo(String value) {
            addCriterion("vt1 >=", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1LessThan(String value) {
            addCriterion("vt1 <", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1LessThanOrEqualTo(String value) {
            addCriterion("vt1 <=", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1Like(String value) {
            addCriterion("vt1 like", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1NotLike(String value) {
            addCriterion("vt1 not like", value, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1In(List<String> values) {
            addCriterion("vt1 in", values, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1NotIn(List<String> values) {
            addCriterion("vt1 not in", values, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1Between(String value1, String value2) {
            addCriterion("vt1 between", value1, value2, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt1NotBetween(String value1, String value2) {
            addCriterion("vt1 not between", value1, value2, "vt1");
            return (Criteria) this;
        }

        public Criteria andVt2IsNull() {
            addCriterion("vt2 is null");
            return (Criteria) this;
        }

        public Criteria andVt2IsNotNull() {
            addCriterion("vt2 is not null");
            return (Criteria) this;
        }

        public Criteria andVt2EqualTo(String value) {
            addCriterion("vt2 =", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2NotEqualTo(String value) {
            addCriterion("vt2 <>", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2GreaterThan(String value) {
            addCriterion("vt2 >", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2GreaterThanOrEqualTo(String value) {
            addCriterion("vt2 >=", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2LessThan(String value) {
            addCriterion("vt2 <", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2LessThanOrEqualTo(String value) {
            addCriterion("vt2 <=", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2Like(String value) {
            addCriterion("vt2 like", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2NotLike(String value) {
            addCriterion("vt2 not like", value, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2In(List<String> values) {
            addCriterion("vt2 in", values, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2NotIn(List<String> values) {
            addCriterion("vt2 not in", values, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2Between(String value1, String value2) {
            addCriterion("vt2 between", value1, value2, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt2NotBetween(String value1, String value2) {
            addCriterion("vt2 not between", value1, value2, "vt2");
            return (Criteria) this;
        }

        public Criteria andVt3IsNull() {
            addCriterion("vt3 is null");
            return (Criteria) this;
        }

        public Criteria andVt3IsNotNull() {
            addCriterion("vt3 is not null");
            return (Criteria) this;
        }

        public Criteria andVt3EqualTo(String value) {
            addCriterion("vt3 =", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3NotEqualTo(String value) {
            addCriterion("vt3 <>", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3GreaterThan(String value) {
            addCriterion("vt3 >", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3GreaterThanOrEqualTo(String value) {
            addCriterion("vt3 >=", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3LessThan(String value) {
            addCriterion("vt3 <", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3LessThanOrEqualTo(String value) {
            addCriterion("vt3 <=", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3Like(String value) {
            addCriterion("vt3 like", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3NotLike(String value) {
            addCriterion("vt3 not like", value, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3In(List<String> values) {
            addCriterion("vt3 in", values, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3NotIn(List<String> values) {
            addCriterion("vt3 not in", values, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3Between(String value1, String value2) {
            addCriterion("vt3 between", value1, value2, "vt3");
            return (Criteria) this;
        }

        public Criteria andVt3NotBetween(String value1, String value2) {
            addCriterion("vt3 not between", value1, value2, "vt3");
            return (Criteria) this;
        }

        public Criteria andFvt1IsNull() {
            addCriterion("fvt1 is null");
            return (Criteria) this;
        }

        public Criteria andFvt1IsNotNull() {
            addCriterion("fvt1 is not null");
            return (Criteria) this;
        }

        public Criteria andFvt1EqualTo(String value) {
            addCriterion("fvt1 =", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1NotEqualTo(String value) {
            addCriterion("fvt1 <>", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1GreaterThan(String value) {
            addCriterion("fvt1 >", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1GreaterThanOrEqualTo(String value) {
            addCriterion("fvt1 >=", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1LessThan(String value) {
            addCriterion("fvt1 <", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1LessThanOrEqualTo(String value) {
            addCriterion("fvt1 <=", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1Like(String value) {
            addCriterion("fvt1 like", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1NotLike(String value) {
            addCriterion("fvt1 not like", value, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1In(List<String> values) {
            addCriterion("fvt1 in", values, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1NotIn(List<String> values) {
            addCriterion("fvt1 not in", values, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1Between(String value1, String value2) {
            addCriterion("fvt1 between", value1, value2, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt1NotBetween(String value1, String value2) {
            addCriterion("fvt1 not between", value1, value2, "fvt1");
            return (Criteria) this;
        }

        public Criteria andFvt2IsNull() {
            addCriterion("fvt2 is null");
            return (Criteria) this;
        }

        public Criteria andFvt2IsNotNull() {
            addCriterion("fvt2 is not null");
            return (Criteria) this;
        }

        public Criteria andFvt2EqualTo(String value) {
            addCriterion("fvt2 =", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2NotEqualTo(String value) {
            addCriterion("fvt2 <>", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2GreaterThan(String value) {
            addCriterion("fvt2 >", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2GreaterThanOrEqualTo(String value) {
            addCriterion("fvt2 >=", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2LessThan(String value) {
            addCriterion("fvt2 <", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2LessThanOrEqualTo(String value) {
            addCriterion("fvt2 <=", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2Like(String value) {
            addCriterion("fvt2 like", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2NotLike(String value) {
            addCriterion("fvt2 not like", value, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2In(List<String> values) {
            addCriterion("fvt2 in", values, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2NotIn(List<String> values) {
            addCriterion("fvt2 not in", values, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2Between(String value1, String value2) {
            addCriterion("fvt2 between", value1, value2, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt2NotBetween(String value1, String value2) {
            addCriterion("fvt2 not between", value1, value2, "fvt2");
            return (Criteria) this;
        }

        public Criteria andFvt3IsNull() {
            addCriterion("fvt3 is null");
            return (Criteria) this;
        }

        public Criteria andFvt3IsNotNull() {
            addCriterion("fvt3 is not null");
            return (Criteria) this;
        }

        public Criteria andFvt3EqualTo(String value) {
            addCriterion("fvt3 =", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3NotEqualTo(String value) {
            addCriterion("fvt3 <>", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3GreaterThan(String value) {
            addCriterion("fvt3 >", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3GreaterThanOrEqualTo(String value) {
            addCriterion("fvt3 >=", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3LessThan(String value) {
            addCriterion("fvt3 <", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3LessThanOrEqualTo(String value) {
            addCriterion("fvt3 <=", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3Like(String value) {
            addCriterion("fvt3 like", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3NotLike(String value) {
            addCriterion("fvt3 not like", value, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3In(List<String> values) {
            addCriterion("fvt3 in", values, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3NotIn(List<String> values) {
            addCriterion("fvt3 not in", values, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3Between(String value1, String value2) {
            addCriterion("fvt3 between", value1, value2, "fvt3");
            return (Criteria) this;
        }

        public Criteria andFvt3NotBetween(String value1, String value2) {
            addCriterion("fvt3 not between", value1, value2, "fvt3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table chat_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}